name: Build Docker Image For Unison

on:
  workflow_dispatch:

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set current date as env variable
        run: echo "BuildTime=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Make Unison
        uses: docker/build-push-action@v2
        with:
          context: ./unison
          file: ./unison/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/unison:${{ env.BuildTime }}
            ${{ secrets.DOCKERHUB_USERNAME }}/unison:latest